### ISSUE TITLE
Error when attempting to go build -o dnssearch main.go

### ISSUE THREAD

**Issue by danindiana** [evilsocket/dnssearch#19]
When I attempt to go build -o dnssearch main.go I get the following: 

main.go:18:2: cannot find package "github.com/evilsocket/brutemachine" in any of:
	/snap/go/1473/src/github.com/evilsocket/brutemachine (from $GOROOT)
	/home/broch/src/github.com/evilsocket/brutemachine (from $GOPATH)
main.go:19:2: cannot find package "github.com/fatih/color" in any of:
	/snap/go/1473/src/github.com/fatih/color (from $GOROOT)
	/home/broch/src/github.com/fatih/color (from $GOPATH)
/home/broch/src/github.com/bobesa/go-domain-util/domainutil/util.go:5:2: cannot find package "golang.org/x/net/idna" in any of:
	/snap/go/1473/src/golang.org/x/net/idna (from $GOROOT)
	/home/broch/src/golang.org/x/net/idna (from $GOPATH)

go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/broch/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/broch"
GORACE=""
GOROOT="/snap/go/1473"
GOTMPDIR=""
GOTOOLDIR="/snap/go/1473/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build657428982=/tmp/go-build -gno-record-gcc-switches"

broch@broch-desktop
 OS: Ubuntu 16.04 xenial
 Kernel: x86_64 Linux 4.13.0-37-generic
 Uptime: 3h 55m
 Packages: 2904
 Shell: bash 4.3.48
 Resolution: 2560x1080
 DE: Unity 7.4.5
 WM: Compiz
 WM Theme: Radiance
Radiance [GTK2]
, Radiance [GTK3]
 Icon Theme: ubuntu-mono-light
 Font: Ubuntu 11
 CPU: AMD Ryzen 5 1600X Six-Core @ 4GHz
 GPU: GeForce GTX 1050
 RAM: 9729MiB / 16034MiB

**Comment by evilsocket** [comment]
`go get ./... && go build -o dnssearch main.go`
