### ISSUE TITLE
Dealing with wildcard enabled subdomain

### ISSUE THREAD

**Issue by ehsandeep** [evilsocket/dnssearch#5]
Hello, great work, but i am not sure how it will deal with domains which have wildcard entry (*), enabled for subdomains, for those i see can **dnssearch** showing every result from `names.txt` which is not correct!

**Comment by Trozz** [comment]
maybe have a limit, e.g. if 10 results share the same IP then assume wildcard?

**Comment by evilsocket** [comment]
Or just:

1. Create a random string at the very beginning.
2. If <that-random-string>.domain.tld resolves, it means it has a wildcard entry.

I'll work on it as soon as I have some time ;)

**Comment by ehsandeep** [comment]
yeah, this idea is also good.

**Comment by DavidWittman** [comment]
> 1. Create a random string at the very beginning.
> 2. If .domain.tld resolves, it means it has a wildcard entry.

You can query `*.example.com` and it will return if there is a wildcard entry. I wasn't able to do this with `net.LookupHost` for some reason though.
