### ISSUE TITLE
Use ENTRYPOINT instead of CMD in Dockerfile

### ISSUE THREAD

**Issue by Ucnt** [evilsocket/dnssearch#9]
AWESOME work!  Thanks!

Might be good to use ENTRYPOINT instead of CMD in the dockerfile.  After build and run, as shown, below is what occurs:

docker run -it --rm dnssearch -domain google.com
docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"-domain\": executable file not found in $PATH".

When changed to 'ENTRYPOINT ["/app/dnssearch"]' the below commands work:

docker run -it --rm dnssearch -domain google.com

docker run -it --rm dnssearch -domain google.com -consumers 10

**Comment by DavidWittman** [comment]
This was closed by #10
